# Generated by Django 5.0.6 on 2026-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=5)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
