# Generated by Django 5.0.6 on 2026-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_storycategory_story_storymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='tagline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
