# Generated by Django 5.0.6 on 2026-06-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_school_hero_image_url_school_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
