# Generated by Django 5.0.6 on 2026-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_educator_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='long_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='educator',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
