# Generated by Django 5.0.6 on 2026-06-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_educator_linkedin_url_educator_long_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, help_text="Group materials under a heading, e.g. 'Mathematics' or 'UPSC'.", max_length=120)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('slides', 'Slides'), ('video', 'Video'), ('link', 'Link'), ('other', 'Other')], default='pdf', max_length=10)),
                ('url', models.URLField(help_text='Link to the file or resource (PDF, Drive, YouTube, etc.).')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
