# Generated by Django 5.0.6 on 2026-06-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, help_text='Optional link opened when the notice is clicked.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
