# Generated by Django 5.0.6 on 2026-06-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_tickeritem'),
        ('courses', '0006_lesson_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_links', to='courses.course')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_courses', to='content.learningpath')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('path', 'course')},
            },
        ),
    ]
