# Generated by Django 5.0.6 on 2026-06-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=191),
        ),
        migrations.AddField(
            model_name='course',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='migration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='original_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='source_platform',
            field=models.CharField(choices=[('native', 'Native (created here)'), ('learnworlds', 'LearnWorlds'), ('csv', 'CSV import'), ('other', 'Other')], default='native', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=191),
        ),
        migrations.AddField(
            model_name='lesson',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='migration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='original_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_platform',
            field=models.CharField(choices=[('native', 'Native (created here)'), ('learnworlds', 'LearnWorlds'), ('csv', 'CSV import'), ('other', 'Other')], default='native', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=191),
        ),
        migrations.AddField(
            model_name='module',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='migration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='original_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='source_platform',
            field=models.CharField(choices=[('native', 'Native (created here)'), ('learnworlds', 'LearnWorlds'), ('csv', 'CSV import'), ('other', 'Other')], default='native', max_length=20),
        ),
    ]
