# Generated by Django 5.0.6 on 2026-06-03 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_backfill_course_status'),
        ('live_sessions', '0002_event_livesession_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='live_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_links', to='live_sessions.livesession'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('video', 'Video'), ('text', 'Text'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('live_class', 'Live Class')], default='youtube', max_length=20),
        ),
    ]
