# Generated by Django 5.0.6 on 2026-06-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_live_session_lesson_resource_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
