# Generated by Django 5.0.6 on 2026-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_category_user_city_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('content_manager', 'Content Manager'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
