# Generated by Django 5.0.6 on 2026-06-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher_applicant', 'Teacher Applicant'), ('course_creator', 'Course Creator'), ('mentor', 'Mentor'), ('content_manager', 'Content Manager'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
