"use client";

import { useState } from "react";
import { getCoursePublicSummary, type CourseSummary } from "@/lib/assistant";

export default function CourseAISummary({ slug }: { slug: string }) {
  const [data, setData] = useState<CourseSummary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [open, setOpen] = useState(false);

  async function generate() {
    if (data) {
      setOpen((o) => !o);
      return;
    }
    setLoading(true);
    setError("");
    try {
      const d = await getCoursePublicSummary(slug);
      setData(d);
      setOpen(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't generate summary");
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="mt-8 overflow-hidden rounded-2xl border border-nal-border bg-white shadow-soft">
      <div className="flex items-center justify-between gap-4 border-b border-nal-border bg-nal-parchment/50 px-5 py-4">
        <div className="flex items-center gap-3">
          <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-nal-saffron to-nal-gold text-white">
            <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 3l1.9 4.6L18.5 9l-4.6 1.9L12 15l-1.9-4.1L5.5 9l4.6-1.4L12 3z" />
              <path d="M19 14l.8 2 2 .8-2 .8-.8 2-.8-2-2-.8 2-.8.8-2z" />
            </svg>
          </span>
          <div>
            <h2 className="font-display text-lg font-bold text-nal-navy">AI Summary</h2>
            <p className="text-xs text-nal-slate">A quick AI-generated overview of this course.</p>
          </div>
        </div>
        <button
          onClick={generate}
          disabled={loading}
          className="shrink-0 rounded-lg bg-nal-navy px-4 py-2 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-nal-ink disabled:opacity-60"
        >
          {loading ? "Generating…" : data ? (open ? "Hide" : "Show") : "Generate summary"}
        </button>
      </div>

      {error && <p className="px-5 py-4 text-sm text-nal-terracotta">{error}</p>}

      {data && open && (
        <div className="space-y-5 px-5 py-5 text-sm text-nal-slate">
          <p className="text-base text-nal-navy">{data.short_summary}</p>

          {data.learning_outcomes?.length > 0 && (
            <div>
              <h3 className="font-semibold text-nal-navy">What you&apos;ll learn</h3>
              <ul className="mt-2 space-y-1.5">
                {data.learning_outcomes.map((o, i) => (
                  <li key={i} className="flex gap-2"><span className="text-nal-saffron">✓</span>{o}</li>
                ))}
              </ul>
            </div>
          )}

          {data.key_takeaways?.length > 0 && (
            <div>
              <h3 className="font-semibold text-nal-navy">Key takeaways</h3>
              <ul className="mt-2 space-y-1.5">
                {data.key_takeaways.map((o, i) => (
                  <li key={i} className="flex gap-2"><span className="text-nal-saffron">•</span>{o}</li>
                ))}
              </ul>
            </div>
          )}

          {data.who_should_take?.length > 0 && (
            <div>
              <h3 className="font-semibold text-nal-navy">Who should take this</h3>
              <ul className="mt-2 space-y-1.5">
                {data.who_should_take.map((o, i) => (
                  <li key={i} className="flex gap-2"><span className="text-nal-saffron">→</span>{o}</li>
                ))}
              </ul>
            </div>
          )}

          <p className="border-t border-nal-border pt-3 text-xs text-nal-slate/80">
            ✨ Generated by AI · may contain inaccuracies — always refer to the full course content.
          </p>
        </div>
      )}
    </section>
  );
}
