# Generated by Django 5.0.6 on 2026-06-02 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('webinar', 'Webinar'), ('live_class', 'Live Class'), ('offline_event', 'Offline Event'), ('community_event', 'Community Event')], default='workshop', max_length=20)),
                ('speaker_name', models.CharField(blank=True, max_length=150)),
                ('speaker_title', models.CharField(blank=True, max_length=150)),
                ('speaker_photo_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('online_url', models.URLField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('registration_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='is_recording_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='recording_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='livesession',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='attendance_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('missed', 'Missed')], default='registered', max_length=20),
        ),
    ]
