# Generated by Django 5.0.6 on 2026-06-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_event_livesession_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('24h', '24 hours before'), ('30m', '30 minutes before')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='live_sessions.livesession')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('session', 'kind')},
            },
        ),
    ]
